//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.2+b2c9b29
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "globalSecurityHeadersSettings"
	/// <summary>Global - Security Headers Settings</summary>
	public partial interface IGlobalSecurityHeadersSettings : IPublishedContent
	{
		/// <summary>Content-Security-Policy (CSP)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContentSecurityPolicyCsp { get; }

		/// <summary>Content-Security-Policy-Report-Only</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		bool ContentSecurityPolicyReportOnly { get; }

		/// <summary>Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		bool Enabled { get; }

		/// <summary>Hsts Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		bool HstsEnabled { get; }

		/// <summary>Hsts Include Sub Domains</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		bool HstsIncludeSubDomains { get; }

		/// <summary>Hsts Max Age Seconds</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		int HstsMaxAgeSeconds { get; }

		/// <summary>Hsts Preload</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		bool HstsPreload { get; }

		/// <summary>Permissions-Policy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PermissionsPolicy { get; }

		/// <summary>Referrer-Policy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ReferrerPolicy { get; }

		/// <summary>X-Content-Type-Options</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string XContentTypeOptions { get; }

		/// <summary>X-Frame-Options</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string XFrameOptions { get; }
	}

	/// <summary>Global - Security Headers Settings</summary>
	[PublishedModel("globalSecurityHeadersSettings")]
	public partial class GlobalSecurityHeadersSettings : PublishedContentModel, IGlobalSecurityHeadersSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public new const string ModelTypeAlias = "globalSecurityHeadersSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalSecurityHeadersSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalSecurityHeadersSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Content-Security-Policy (CSP): Defines which sources of content are allowed to load (defends against XSS/injection). Very powerful but easy to break the site — test with Report-Only first. If set without frame-ancestors, it is appended automatically so preview keeps working. Blank: the system auto-generates frame-ancestors to allow backoffice preview.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contentSecurityPolicyCsp")]
		public virtual string ContentSecurityPolicyCsp => GetContentSecurityPolicyCsp(this, _publishedValueFallback);

		/// <summary>Static getter for Content-Security-Policy (CSP)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContentSecurityPolicyCsp(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "contentSecurityPolicyCsp");

		///<summary>
		/// Content-Security-Policy-Report-Only: On = the CSP only reports violations without blocking (safe for testing).  Off = the CSP is enforced (actually blocks).  
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[ImplementPropertyType("contentSecurityPolicyReportOnly")]
		public virtual bool ContentSecurityPolicyReportOnly => GetContentSecurityPolicyReportOnly(this, _publishedValueFallback);

		/// <summary>Static getter for Content-Security-Policy-Report-Only</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public static bool GetContentSecurityPolicyReportOnly(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "contentSecurityPolicyReportOnly");

		///<summary>
		/// Enabled: Master switch for this site's security headers. When off, no security headers are sent at all. Must be on for the settings below to take effect.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[ImplementPropertyType("enabled")]
		public virtual bool Enabled => GetEnabled(this, _publishedValueFallback);

		/// <summary>Static getter for Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public static bool GetEnabled(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "enabled");

		///<summary>
		/// Hsts Enabled: Forces browsers to always use HTTPS for this domain. Sent only over HTTPS connections. Use with care: once sent with a long duration it is hard to undo.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[ImplementPropertyType("hstsEnabled")]
		public virtual bool HstsEnabled => GetHstsEnabled(this, _publishedValueFallback);

		/// <summary>Static getter for Hsts Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public static bool GetHstsEnabled(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "hstsEnabled");

		///<summary>
		/// Hsts Include Sub Domains: Applies HSTS to all subdomains.  Enable only when every subdomain serves HTTPS.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[ImplementPropertyType("hstsIncludeSubDomains")]
		public virtual bool HstsIncludeSubDomains => GetHstsIncludeSubDomains(this, _publishedValueFallback);

		/// <summary>Static getter for Hsts Include Sub Domains</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public static bool GetHstsIncludeSubDomains(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "hstsIncludeSubDomains");

		///<summary>
		/// Hsts Max Age Seconds: How long (in seconds) the browser remembers to use HTTPS only.  Blank or 0 = default 31536000 (1 year).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[ImplementPropertyType("hstsMaxAgeSeconds")]
		public virtual int HstsMaxAgeSeconds => GetHstsMaxAgeSeconds(this, _publishedValueFallback);

		/// <summary>Static getter for Hsts Max Age Seconds</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public static int GetHstsMaxAgeSeconds(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "hstsMaxAgeSeconds");

		///<summary>
		/// Hsts Preload: Requests inclusion in the browsers' HSTS preload list.  Enable only if you understand the implications (requires max-age ≥ 1 year + includeSubDomains, and is hard to remove from the list).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[ImplementPropertyType("hstsPreload")]
		public virtual bool HstsPreload => GetHstsPreload(this, _publishedValueFallback);

		/// <summary>Static getter for Hsts Preload</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		public static bool GetHstsPreload(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "hstsPreload");

		///<summary>
		/// Permissions-Policy: Restricts access to browser features (camera, microphone, geolocation, etc.). Example: camera=(), microphone=(), geolocation=().
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("permissionsPolicy")]
		public virtual string PermissionsPolicy => GetPermissionsPolicy(this, _publishedValueFallback);

		/// <summary>Static getter for Permissions-Policy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPermissionsPolicy(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "permissionsPolicy");

		///<summary>
		/// Referrer-Policy: Controls how much referrer information is sent when navigating away. Recommended: strict-origin-when-cross-origin.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("referrerPolicy")]
		public virtual string ReferrerPolicy => GetReferrerPolicy(this, _publishedValueFallback);

		/// <summary>Static getter for Referrer-Policy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetReferrerPolicy(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "referrerPolicy");

		///<summary>
		/// X-Content-Type-Options: Stops browsers from MIME-sniffing (guessing a file's type). Leave blank to use the default nosniff (recommended).  Only nosniff or blank is meaningful.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("xContentTypeOptions")]
		public virtual string XContentTypeOptions => GetXContentTypeOptions(this, _publishedValueFallback);

		/// <summary>Static getter for X-Content-Type-Options</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetXContentTypeOptions(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "xContentTypeOptions");

		///<summary>
		/// X-Frame-Options: Prevents the site from being embedded in an iframe (clickjacking).  Blank = SAMEORIGIN.  Note: this applies only when no CSP is set and no backoffice host is configured; when a backoffice host exists the system uses CSP frame-ancestors instead and ignores this field.  Valid values: SAMEORIGIN or DENY.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("xFrameOptions")]
		public virtual string XFrameOptions => GetXFrameOptions(this, _publishedValueFallback);

		/// <summary>Static getter for X-Frame-Options</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.2+b2c9b29")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetXFrameOptions(IGlobalSecurityHeadersSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "xFrameOptions");
	}
}
