//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.6.1+bdb98f0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Global - Folder Settings</summary>
	[PublishedModel("globalFolderSettings")]
	public partial class GlobalFolderSettings : PublishedContentModel, IGlobalResponsiveImageSettings, IGlobalSmtpSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		public new const string ModelTypeAlias = "globalFolderSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalFolderSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalFolderSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Disable: When ON, the "Remember Language" feature is disabled. Visitors will not be auto-redirected to their previously selected language.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("rememberLanguageDisable")]
		public virtual bool RememberLanguageDisable => this.Value<bool>(_publishedValueFallback, "rememberLanguageDisable");

		///<summary>
		/// Content: Raw content for the robots.txt file. Example: User-agent: * Disallow: /umbraco/ Sitemap: https://www.example.com/sitemap.xml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("robotsContent")]
		public virtual string RobotsContent => this.Value<string>(_publishedValueFallback, "robotsContent");

		///<summary>
		/// Ignored Document Types: Content based on these document types will be ignored on the sitemap use alias of the document types
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sitemapIgnoredDocumentTypes")]
		public virtual global::System.Collections.Generic.IEnumerable<string> SitemapIgnoredDocumentTypes => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "sitemapIgnoredDocumentTypes");

		///<summary>
		/// Max Sitemap Depth: Maximum tree depth to include in the sitemap.xml. Leave empty for no limit.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("sitemapMaxSitemapDepth")]
		public virtual int SitemapMaxSitemapDepth => this.Value<int>(_publishedValueFallback, "sitemapMaxSitemapDepth");

		///<summary>
		/// Site Title Suffix: Syntax: "\{titlePage\}": Default if is empty "\{titleSiteName\}": Site Name config in Folder Sites
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteTitleSuffix")]
		public virtual string SiteTitleSuffix => this.Value<string>(_publishedValueFallback, "siteTitleSuffix");

		///<summary>
		/// Turn Off AppSettings: Use the config here to make SMTP settings instead of the AppSettings config
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("turnOffAppSettings")]
		public virtual bool TurnOffAppSettings => this.Value<bool>(_publishedValueFallback, "turnOffAppSettings");

		///<summary>
		/// Extend Sizes SrcSet: Additional dimensions used for the img tag's srcset data If not entered, default will only take 3 sizes for srcset Default: 1200w (Desktop), 1024w (Table), 768w (Mobile)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("repImgExtendSizesSrcSet")]
		public virtual global::System.Collections.Generic.IEnumerable<string> RepImgExtendSizesSrcSet => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalResponsiveImageSettings.GetRepImgExtendSizesSrcSet(this, _publishedValueFallback);

		///<summary>
		/// Turn Off Responsive Image: When ON, responsive images are disabled — Image url links will be resized and converted to .webp format.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("repImgTurnOffResponsiveImage")]
		public virtual bool RepImgTurnOffResponsiveImage => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalResponsiveImageSettings.GetRepImgTurnOffResponsiveImage(this, _publishedValueFallback);

		///<summary>
		/// Credential Password: SMTP authentication password or app-specific password.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpCredentialPassword")]
		public virtual string SmtpCredentialPassword => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpCredentialPassword(this, _publishedValueFallback);

		///<summary>
		/// Credential Username: SMTP authentication username. Leave empty if no authentication is required.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpCredentialUsername")]
		public virtual string SmtpCredentialUsername => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpCredentialUsername(this, _publishedValueFallback);

		///<summary>
		/// Email From: Sender email address for outgoing emails (e.g. noreply@example.com).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpEmailFrom")]
		public virtual string SmtpEmailFrom => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpEmailFrom(this, _publishedValueFallback);

		///<summary>
		/// Enable Ssl: Enable SSL/TLS encryption for SMTP connection. Most providers require this.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("smtpEnableSsl")]
		public virtual bool SmtpEnableSsl => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpEnableSsl(this, _publishedValueFallback);

		///<summary>
		/// Host: SMTP server hostname (e.g. smtp.gmail.com, smtp.sendgrid.net).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpHost")]
		public virtual string SmtpHost => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpHost(this, _publishedValueFallback);

		///<summary>
		/// Port: SMTP server port number. Common values: 587 (TLS), 465 (SSL), 25 (unencrypted).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("smtpPort")]
		public virtual int SmtpPort => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpPort(this, _publishedValueFallback);
	}
}
