//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.6.1+bdb98f0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Global Navigation Item</summary>
	[PublishedModel("globalNavigationItem")]
	public partial class GlobalNavigationItem : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		public new const string ModelTypeAlias = "globalNavigationItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalNavigationItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalNavigationItem(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Add "noopener" to link: Adds rel="noopener" to the link. Recommended for external links opened in a new tab to prevent security vulnerabilities.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("navAddNoopenerToLink")]
		public virtual bool NavAddNoopenerToLink => this.Value<bool>(_publishedValueFallback, "navAddNoopenerToLink");

		///<summary>
		/// Add "noreferrer" to link: Adds rel="noreferrer" to the link. Prevents sending referrer information when navigating to external sites.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("navAddNoreferrerToLink")]
		public virtual bool NavAddNoreferrerToLink => this.Value<bool>(_publishedValueFallback, "navAddNoreferrerToLink");

		///<summary>
		/// Children: For multi-level menus
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("navChildren")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel NavChildren => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "navChildren");

		///<summary>
		/// Hidden Item: When ON, this navigation item is hidden from the menu output.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("navHiddenItem")]
		public virtual bool NavHiddenItem => this.Value<bool>(_publishedValueFallback, "navHiddenItem");

		///<summary>
		/// Hide if member is logged in: When ON, this item is hidden for authenticated (logged-in) members. Useful for "Login" links.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("navHideIfMemberIsLoggedIn")]
		public virtual bool NavHideIfMemberIsLoggedIn => this.Value<bool>(_publishedValueFallback, "navHideIfMemberIsLoggedIn");

		///<summary>
		/// Hide if member is logged out: When ON, this item is hidden for unauthenticated (logged-out) visitors. Useful for "My Account" links.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("navHideIfMemberIsLoggedOut")]
		public virtual bool NavHideIfMemberIsLoggedOut => this.Value<bool>(_publishedValueFallback, "navHideIfMemberIsLoggedOut");

		///<summary>
		/// Hide label: When ON, the link text label is visually hidden (useful for icon-only navigation items).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("navHideLabel")]
		public virtual bool NavHideLabel => this.Value<bool>(_publishedValueFallback, "navHideLabel");

		///<summary>
		/// Include Child Nodes: Automatically includes child links defined within the parent navLink.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[ImplementPropertyType("navIncludeChildNodes")]
		public virtual bool NavIncludeChildNodes => this.Value<bool>(_publishedValueFallback, "navIncludeChildNodes");

		///<summary>
		/// Inner CSS Class: Example: Using css class tag a
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("navInnerCssClass")]
		public virtual string NavInnerCssClass => this.Value<string>(_publishedValueFallback, "navInnerCssClass");

		///<summary>
		/// Link: Navigation link URL. Pick an internal page or enter an external URL (e.g. https://example.com/page).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("navLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link NavLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "navLink");

		///<summary>
		/// Outer CSS Class: Example: Using css class tag li
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.1+bdb98f0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("navOuterCSSClass")]
		public virtual string NavOuterCssclass => this.Value<string>(_publishedValueFallback, "navOuterCSSClass");
	}
}
