//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "uTPro__PageListBase"
	/// <summary>uTPro - Page List Base</summary>
	public partial interface IUTpro__PageListBase : IPublishedElement
	{
		/// <summary>Filter by Category</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> PageListFilterCategory { get; }

		/// <summary>Items Per Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		int PageListItemsPerPage { get; }

		/// <summary>Layout Style</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PageListLayout { get; }

		/// <summary>Max Depth</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		int PageListMaxDepth { get; }

		/// <summary>Max Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		int PageListMaxItems { get; }

		/// <summary>Order By</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PageListOrderBy { get; }

		/// <summary>Order Direction</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PageListOrderDirection { get; }

		/// <summary>Show Categories</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		bool PageListShowCategories { get; }

		/// <summary>Show Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		bool PageListShowDate { get; }

		/// <summary>Show Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		bool PageListShowDescription { get; }

		/// <summary>Show Thumbnail</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		bool PageListShowThumbnail { get; }

		/// <summary>Source</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> PageListSource { get; }
	}

	/// <summary>uTPro - Page List Base</summary>
	[PublishedModel("uTPro__PageListBase")]
	public partial class UTpro__PageListBase : PublishedElementModel, IUTpro__PageListBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "uTPro__PageListBase";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<UTpro__PageListBase, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public UTpro__PageListBase(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Filter by Category: Only show pages assigned to these categories. Empty = show all.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListFilterCategory")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> PageListFilterCategory => GetPageListFilterCategory(this, _publishedValueFallback);

		/// <summary>Static getter for Filter by Category</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> GetPageListFilterCategory(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>>(publishedValueFallback, "pageListFilterCategory");

		///<summary>
		/// Items Per Page: Number of items per page. Default: 10.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("pageListItemsPerPage")]
		public virtual int PageListItemsPerPage => GetPageListItemsPerPage(this, _publishedValueFallback);

		/// <summary>Static getter for Items Per Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public static int GetPageListItemsPerPage(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "pageListItemsPerPage");

		///<summary>
		/// Layout Style: Layout: list, grid-2col, or grid-3col. Default: list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListLayout")]
		public virtual string PageListLayout => GetPageListLayout(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Style</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPageListLayout(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "pageListLayout");

		///<summary>
		/// Max Depth: How many levels deep to search for pages. 1 = direct children only. Default: 1.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("pageListMaxDepth")]
		public virtual int PageListMaxDepth => GetPageListMaxDepth(this, _publishedValueFallback);

		/// <summary>Static getter for Max Depth</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public static int GetPageListMaxDepth(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "pageListMaxDepth");

		///<summary>
		/// Max Items: Maximum total items to display. 0 = no limit (show all).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("pageListMaxItems")]
		public virtual int PageListMaxItems => GetPageListMaxItems(this, _publishedValueFallback);

		/// <summary>Static getter for Max Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public static int GetPageListMaxItems(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "pageListMaxItems");

		///<summary>
		/// Order By: Sort field: sortOrder, createDate, updateDate, or name. Default: sortOrder.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListOrderBy")]
		public virtual string PageListOrderBy => GetPageListOrderBy(this, _publishedValueFallback);

		/// <summary>Static getter for Order By</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPageListOrderBy(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "pageListOrderBy");

		///<summary>
		/// Order Direction: Sort direction: asc or desc. Default: asc.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListOrderDirection")]
		public virtual string PageListOrderDirection => GetPageListOrderDirection(this, _publishedValueFallback);

		/// <summary>Static getter for Order Direction</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPageListOrderDirection(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "pageListOrderDirection");

		///<summary>
		/// Show Categories: Display category badges/tags for each item.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("pageListShowCategories")]
		public virtual bool PageListShowCategories => GetPageListShowCategories(this, _publishedValueFallback);

		/// <summary>Static getter for Show Categories</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public static bool GetPageListShowCategories(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "pageListShowCategories");

		///<summary>
		/// Show Date: Display the publish/create date in the list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("pageListShowDate")]
		public virtual bool PageListShowDate => GetPageListShowDate(this, _publishedValueFallback);

		/// <summary>Static getter for Show Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public static bool GetPageListShowDate(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "pageListShowDate");

		///<summary>
		/// Show Description: Display the page description/excerpt in the list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("pageListShowDescription")]
		public virtual bool PageListShowDescription => GetPageListShowDescription(this, _publishedValueFallback);

		/// <summary>Static getter for Show Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public static bool GetPageListShowDescription(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "pageListShowDescription");

		///<summary>
		/// Show Thumbnail: Display the page thumbnail image in the list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("pageListShowThumbnail")]
		public virtual bool PageListShowThumbnail => GetPageListShowThumbnail(this, _publishedValueFallback);

		/// <summary>Static getter for Show Thumbnail</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public static bool GetPageListShowThumbnail(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "pageListShowThumbnail");

		///<summary>
		/// Source: Select the Pages folder node to list children from. If empty, uses the current page's parent.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListSource")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> PageListSource => GetPageListSource(this, _publishedValueFallback);

		/// <summary>Static getter for Source</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> GetPageListSource(IUTpro__PageListBase that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>>(publishedValueFallback, "pageListSource");
	}
}
