//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.6.0+6559750
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>uTPro - Search Results</summary>
	[PublishedModel("uTPro__SearchResults")]
	public partial class UTpro__SearchResults : PublishedElementModel, IUTpro__PageListBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		public new const string ModelTypeAlias = "uTPro__SearchResults";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<UTpro__SearchResults, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public UTpro__SearchResults(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Highlight Keywords: Highlight matching keywords in search results.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("searchHighlightKeywords")]
		public virtual bool SearchHighlightKeywords => this.Value<bool>(_publishedValueFallback, "searchHighlightKeywords");

		///<summary>
		/// Min Characters: Minimum characters required before search executes. Default: 3.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("searchMinChars")]
		public virtual int SearchMinChars => this.Value<int>(_publishedValueFallback, "searchMinChars");

		///<summary>
		/// No Results Message: Message shown when no results found. Empty = uses dictionary key.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchNoResultsMessage")]
		public virtual string SearchNoResultsMessage => this.Value<string>(_publishedValueFallback, "searchNoResultsMessage");

		///<summary>
		/// Search parameter: Default: q
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchParameter")]
		public virtual string SearchParameter => this.Value<string>(_publishedValueFallback, "searchParameter");

		///<summary>
		/// Placeholder: Placeholder text for the search input. Empty = uses dictionary key.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchPlaceholder")]
		public virtual string SearchPlaceholder => this.Value<string>(_publishedValueFallback, "searchPlaceholder");

		///<summary>
		/// Search Scope: Scope: allSite, currentFolder, or selectedSource. Default: selectedSource (uses the Source field from Data Source tab).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchScope")]
		public virtual string SearchScope => this.Value<string>(_publishedValueFallback, "searchScope");

		///<summary>
		/// Filter by Category: Only show pages assigned to these categories. Empty = show all.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListFilterCategory")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> PageListFilterCategory => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListFilterCategory(this, _publishedValueFallback);

		///<summary>
		/// Items Per Page: Number of items per page. Default: 10.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("pageListItemsPerPage")]
		public virtual int PageListItemsPerPage => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListItemsPerPage(this, _publishedValueFallback);

		///<summary>
		/// Layout Style: Layout: list, grid-2col, or grid-3col. Default: list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListLayout")]
		public virtual string PageListLayout => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListLayout(this, _publishedValueFallback);

		///<summary>
		/// Max Depth: How many levels deep to search for pages. 1 = direct children only. Default: 1.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("pageListMaxDepth")]
		public virtual int PageListMaxDepth => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListMaxDepth(this, _publishedValueFallback);

		///<summary>
		/// Max Items: Maximum total items to display. 0 = no limit (show all).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("pageListMaxItems")]
		public virtual int PageListMaxItems => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListMaxItems(this, _publishedValueFallback);

		///<summary>
		/// Order By: Sort field: sortOrder, createDate, updateDate, or name. Default: sortOrder.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListOrderBy")]
		public virtual string PageListOrderBy => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListOrderBy(this, _publishedValueFallback);

		///<summary>
		/// Order Direction: Sort direction: asc or desc. Default: asc.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListOrderDirection")]
		public virtual string PageListOrderDirection => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListOrderDirection(this, _publishedValueFallback);

		///<summary>
		/// Show Categories: Display category badges/tags for each item.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("pageListShowCategories")]
		public virtual bool PageListShowCategories => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListShowCategories(this, _publishedValueFallback);

		///<summary>
		/// Show Date: Display the publish/create date in the list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("pageListShowDate")]
		public virtual bool PageListShowDate => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListShowDate(this, _publishedValueFallback);

		///<summary>
		/// Show Description: Display the page description/excerpt in the list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("pageListShowDescription")]
		public virtual bool PageListShowDescription => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListShowDescription(this, _publishedValueFallback);

		///<summary>
		/// Show Thumbnail: Display the page thumbnail image in the list.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[ImplementPropertyType("pageListShowThumbnail")]
		public virtual bool PageListShowThumbnail => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListShowThumbnail(this, _publishedValueFallback);

		///<summary>
		/// Source: Select the Pages folder node to list children from. If empty, uses the current page's parent.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.6.0+6559750")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageListSource")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> PageListSource => global::Umbraco.Cms.Web.Common.PublishedModels.UTpro__PageListBase.GetPageListSource(this, _publishedValueFallback);
	}
}
