title: uTPro Documentation
description: Developer documentation for uTPro – Umbraco Turbo Pro Starter Kit
url: "https://docs.utpro.dev"
baseurl: ""

compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  blanklines: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  hard_wrap: false

# Sass
sass:
  style: compressed

# Defaults - apply layout to all md files
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "default"
  - scope:
      path: "features"
    values:
      layout: "default"
      feature: true

# SEO
author: T4VN
logo: /Logo.png
social:
  name: T4VN
  links:
    - https://github.com/T4VN
    - https://t4vn.com
