title: uTPro Documentation
description: Developer documentation for uTPro – Umbraco Turbo Pro Starter Kit
url: "https://docs.utpro.dev"
baseurl: ""

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Defaults - apply layout to all md files
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "default"

# SEO
author: T4VN
logo: /Logo.png
social:
  name: T4VN
  links:
    - https://github.com/T4VN
    - https://t4vn.com
