using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using uTPro.Feature.VideoAnalyzer.Configuration;

namespace uTPro.Feature.VideoAnalyzer.Providers;

/// <summary>One transcript line. Property names are intentionally terse — stored as JSON in the DB.</summary>
public sealed record TranscriptSegment(
    [property: JsonPropertyName("s")] double S,
    [property: JsonPropertyName("t")] string T);

/// <summary>
/// Transcript + basic-info source for YouTube via YoutubeExplode (community library).
/// Best-effort by design: cloud IPs are sometimes blocked by YouTube, and not every video
/// has captions — callers must treat failures as non-fatal.
/// </summary>
public interface ITranscriptProvider
{
    /// <summary>Captions for the video, preferring manual over auto-generated and the configured languages first. Null when none usable.</summary>
    Task<List<TranscriptSegment>?> GetTranscriptAsync(string videoId, CancellationToken cancellationToken);

    /// <summary>Basic metadata fallback when the official Data API is unavailable.</summary>
    Task<VideoMetadata?> GetBasicInfoAsync(string videoId);
}

internal sealed class TranscriptProvider(
    IOptions<VideoAnalyzerOptions> options,
    ILogger<TranscriptProvider> logger) : ITranscriptProvider
{
    private readonly YoutubeExplode.YoutubeClient _youtube = new();

    public async Task<List<TranscriptSegment>?> GetTranscriptAsync(string videoId, CancellationToken cancellationToken)
    {
        try
        {
            var manifest = await _youtube.Videos.ClosedCaptions.GetManifestAsync(videoId, cancellationToken);
            var track = PickTrack(
                manifest.Tracks.Select(t => (Track: t, t.Language.Code, t.IsAutoGenerated)),
                options.Value.PreferredTranscriptLanguages);
            if (track is null)
            {
                logger.LogInformation("VideoAnalyzer: no usable caption track for {VideoId}.", videoId);
                return null;
            }

            var trackContent = await _youtube.Videos.ClosedCaptions.GetAsync(track.Value.Track);
            var segments = trackContent.Captions
                .Select(c => new TranscriptSegment(c.Offset.TotalSeconds, c.Text))
                .Where(s => !string.IsNullOrWhiteSpace(s.T))
                .ToList();
            return segments.Count > 0 ? segments : null;
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            logger.LogWarning(ex, "VideoAnalyzer: transcript capture failed for {VideoId}.", videoId);
            return null;
        }
    }

    public async Task<VideoMetadata?> GetBasicInfoAsync(string videoId)
    {
        try
        {
            var video = await _youtube.Videos.GetAsync(videoId);
            return new VideoMetadata
            {
                Id = videoId,
                Title = video.Title,
                Description = video.Description ?? string.Empty,
                ChannelTitle = video.Author.ChannelTitle,
                ThumbnailUrl = video.Thumbnails
                    .OrderByDescending(t => t.Resolution.Area)
                    .FirstOrDefault()?.Url ?? string.Empty,
                DurationSeconds = (int?)video.Duration?.TotalSeconds ?? 0,
            };
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "VideoAnalyzer: basic info fetch failed for {VideoId}.", videoId);
            return null;
        }
    }

    internal static (YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionTrackInfo Track, string Code, bool Auto)?
        PickTrack(
            IEnumerable<(YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionTrackInfo Track, string Code, bool Auto)> tracks,
            string[] preferredLanguages)
    {
        foreach (var language in preferredLanguages)
        {
            var manual = tracks.FirstOrDefault(t =>
                t.Code.StartsWith(language, StringComparison.OrdinalIgnoreCase) && !t.Auto);
            if (manual.Track is not null)
            {
                return manual;
            }

            var auto = tracks.FirstOrDefault(t =>
                t.Code.StartsWith(language, StringComparison.OrdinalIgnoreCase) && t.Auto);
            if (auto.Track is not null)
            {
                return auto;
            }
        }

        var any = tracks.FirstOrDefault(t => !t.Auto);
        if (any.Track is not null)
        {
            return any;
        }

        var first = tracks.FirstOrDefault();
        return first.Track is not null ? first : null;
    }
}
