//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.4.1+3472ff9
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Global - Folder Settings</summary>
	[PublishedModel("globalFolderSettings")]
	public partial class GlobalFolderSettings : PublishedContentModel, IGlobalSmtpSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		public new const string ModelTypeAlias = "globalFolderSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalFolderSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalFolderSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Disable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("rememberLanguageDisable")]
		public virtual bool RememberLanguageDisable => this.Value<bool>(_publishedValueFallback, "rememberLanguageDisable");

		///<summary>
		/// Turn Off Responsive Image: Turn on: Image url links will be resized and converted to .webp format.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("repImgEnable")]
		public virtual bool RepImgEnable => this.Value<bool>(_publishedValueFallback, "repImgEnable");

		///<summary>
		/// Extend Sizes SrcSet: Additional dimensions used for the img tag's srcset data If not entered, default will only take 3 sizes for srcset
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("repImgExtendSizesSrcSet")]
		public virtual global::System.Collections.Generic.IEnumerable<string> RepImgExtendSizesSrcSet => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "repImgExtendSizesSrcSet");

		///<summary>
		/// Max Width Desktop (px): Default: 1920px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("repImgMaxWidthDesktop")]
		public virtual int RepImgMaxWidthDesktop => this.Value<int>(_publishedValueFallback, "repImgMaxWidthDesktop");

		///<summary>
		/// Max Width Mobile (px): Default: 768px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("repImgMaxWidthMobile")]
		public virtual int RepImgMaxWidthMobile => this.Value<int>(_publishedValueFallback, "repImgMaxWidthMobile");

		///<summary>
		/// Max Width Table (px): Default: 1024px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("repImgMaxWidthTable")]
		public virtual int RepImgMaxWidthTable => this.Value<int>(_publishedValueFallback, "repImgMaxWidthTable");

		///<summary>
		/// Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("robotsContent")]
		public virtual string RobotsContent => this.Value<string>(_publishedValueFallback, "robotsContent");

		///<summary>
		/// Ignored Document Types: Content based on these document types will be ignored on the sitemap use alias of the document types
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sitemapIgnoredDocumentTypes")]
		public virtual global::System.Collections.Generic.IEnumerable<string> SitemapIgnoredDocumentTypes => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "sitemapIgnoredDocumentTypes");

		///<summary>
		/// Max Sitemap Depth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("sitemapMaxSitemapDepth")]
		public virtual int SitemapMaxSitemapDepth => this.Value<int>(_publishedValueFallback, "sitemapMaxSitemapDepth");

		///<summary>
		/// Site Title Suffix: Syntax: "\{titlePage\}": Default if is empty "\{titleSiteName\}": Site Name config in Folder Sites
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteTitleSuffix")]
		public virtual string SiteTitleSuffix => this.Value<string>(_publishedValueFallback, "siteTitleSuffix");

		///<summary>
		/// Turn Off AppSettings: Use the config here to make SMTP settings instead of the AppSettings config
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("turnOffAppSettings")]
		public virtual bool TurnOffAppSettings => this.Value<bool>(_publishedValueFallback, "turnOffAppSettings");

		///<summary>
		/// Credential Password
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpCredentialPassword")]
		public virtual string SmtpCredentialPassword => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpCredentialPassword(this, _publishedValueFallback);

		///<summary>
		/// Credential Username
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpCredentialUsername")]
		public virtual string SmtpCredentialUsername => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpCredentialUsername(this, _publishedValueFallback);

		///<summary>
		/// Email From
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpEmailFrom")]
		public virtual string SmtpEmailFrom => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpEmailFrom(this, _publishedValueFallback);

		///<summary>
		/// Enable Ssl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("smtpEnableSsl")]
		public virtual bool SmtpEnableSsl => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpEnableSsl(this, _publishedValueFallback);

		///<summary>
		/// Host
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpHost")]
		public virtual string SmtpHost => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpHost(this, _publishedValueFallback);

		///<summary>
		/// Port
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.4.1+3472ff9")]
		[ImplementPropertyType("smtpPort")]
		public virtual int SmtpPort => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalSmtpSettings.GetSmtpPort(this, _publishedValueFallback);
	}
}
