<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="App_Plugins\utpro-cms-screen\style.css" />
    <Content Include="App_Plugins\utpro-cms-screen\umbraco-package.json" />
    <Content Include="App_Plugins\utpro-dashboard\umbraco-package.json" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App_Plugins\utpro-cms-screen\index.js" />
    <None Include="App_Plugins\utpro-cms-screen\lang\en-us.js" />
    <None Include="App_Plugins\utpro-dashboard\config.js" />
    <None Include="App_Plugins\utpro-dashboard\dashboard.element.js" />
    <None Include="App_Plugins\utpro-dashboard\header-app.element.js" />
    <None Include="App_Plugins\utpro-dashboard\packages-config.js" />
    <None Include="App_Plugins\utpro-dashboard\vendor\frappe-charts.min.esm.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\uTPro.Common\uTPro.Common.csproj" />
  </ItemGroup>

</Project>
